version: "3.8"
services:
  orthanc-backend:
    image: jodogne/orthanc-plugins 
    container_name: orthweb
    command: /run/secrets/  # Path to the configuration files (stored as secrets)
    ports:
      - 4242:4242
      - 8042:8042
    env_file:
      - /home/ec2-user/.orthanc.env
    secrets:
      - orthanc.json
      - site.pem
  nginx-proxy:
    image: nginx
    container_name: nginx
    ports:
      - 11112:11112 
    volumes:
      - ./dicomtls.conf:/etc/nginx/nginx.conf
      - ./sample.localhost.pem:/etc/nginx/conf.d/site.pem
secrets:
  orthanc.json:
    file: orthanc.json
  site.pem:
    file: sample.localhost.pem
